FROM mcr.microsoft.com/devcontainers/go:1-1.23-bookworm

# [Optional] Install additional tools or dependencies here
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>
